(require 'cask "~/.cask/cask.el")
(cask-initialize)

(load "~/.emacs.d/ui.el")
(load "~/.emacs.d/backups.el")
(load "~/.emacs.d/mac-clipboard.el")
(load "~/.emacs.d/path-fix.el")
(load "~/.emacs.d/helm.el")
(load "~/.emacs.d/projectile.el")
(load "~/.emacs.d/prog-mode.el")
