;;; pebble-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from pebble-mode.el

(autoload 'pebble-mode "pebble-mode" "\
Major mode for editing pebble files.

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.peb\\'" . pebble-mode))
(register-definition-prefixes "pebble-mode" '("pebble-"))

;;; End of scraped data

(provide 'pebble-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; pebble-mode-autoloads.el ends here
