;;; dim-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from dim.el

(autoload 'dim-major-name "dim" "\
Set mode-line name of the major MODE to NEW-NAME.
The change will take effect next time the MODE will be enabled.

(fn MODE NEW-NAME)")
(autoload 'dim-major-names "dim" "\
Change names of major modes according to SPECS list.
Each element of the list should be a list of arguments taken by
`dim-major-name' function.

(fn SPECS)")
(autoload 'dim-minor-name "dim" "\
Set mode-line name of the minor MODE to NEW-NAME.
FILE is a feature or file name where the MODE comes from.  If it
is specified, it is passed to `eval-after-load'.  If it is nil,
MODE name is changed immediately (if the MODE is available).

(fn MODE NEW-NAME &optional FILE)")
(autoload 'dim-minor-names "dim" "\
Change names of minor modes according to SPECS list.
Each element of the list should be a list of arguments taken by
`dim-minor-name' function.

(fn SPECS)")
(register-definition-prefixes "dim" '("dim-"))

;;; End of scraped data

(provide 'dim-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; dim-autoloads.el ends here
